package cn.chinaunicom.ws.srenewser;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.12
 * Tue Apr 17 09:41:55 GMT+08:00 2018
 * Generated source version: 2.2.12
 * 
 */
 
@WebService(targetNamespace = "http://ws.chinaunicom.cn/SrenewSer/", name = "SrenewSer")
@XmlSeeAlso({cn.chinaunicom.ws.srenewser.unibssbody.srenewtradereq.ObjectFactory.class, cn.chinaunicom.ws.unibsshead.ObjectFactory.class, cn.chinaunicom.ws.unibssattached.ObjectFactory.class, cn.chinaunicom.ws.srenewser.unibssbody.srenewtradersp.ObjectFactory.class, cn.chinaunicom.ws.srenewser.unibssbody.qrychgprodreq.ObjectFactory.class, cn.chinaunicom.ws.srenewser.unibssbody.qrychgprodrsp.ObjectFactory.class, cn.chinaunicom.ws.srenewser.unibssbody.srenewsubrsp.ObjectFactory.class, cn.chinaunicom.ws.srenewser.unibssbody.srenewsubreq.ObjectFactory.class, cn.chinaunicom.ws.srenewser.unibssbody.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SrenewSer {

    @WebMethod(action = "http://ws.chinaunicom.cn/SrenewSer/qryChgProd/")
    @WebResult(name = "QRY_CHG_PROD_OUTPUT", targetNamespace = "http://ws.chinaunicom.cn/SrenewSer/unibssBody", partName = "parameters")
    public cn.chinaunicom.ws.srenewser.unibssbody.QRYCHGPRODOUTPUT qryChgProd(
        @WebParam(partName = "parameters", name = "QRY_CHG_PROD_INPUT", targetNamespace = "http://ws.chinaunicom.cn/SrenewSer/unibssBody")
        cn.chinaunicom.ws.srenewser.unibssbody.QRYCHGPRODINPUT parameters
    );

    @WebMethod(action = "http://ws.chinaunicom.cn/SrenewSer/srenewTrade/")
    @WebResult(name = "SRENEW_TRADE_OUTPUT", targetNamespace = "http://ws.chinaunicom.cn/SrenewSer/unibssBody", partName = "parameters")
    public cn.chinaunicom.ws.srenewser.unibssbody.SRENEWTRADEOUTPUT srenewTrade(
        @WebParam(partName = "parameters", name = "SRENEW_TRADE_INPUT", targetNamespace = "http://ws.chinaunicom.cn/SrenewSer/unibssBody")
        cn.chinaunicom.ws.srenewser.unibssbody.SRENEWTRADEINPUT parameters
    );

    @WebMethod(action = "http://ws.chinaunicom.cn/SrenewSer/srenewSub/")
    @WebResult(name = "SRENEW_SUB_OUTPUT", targetNamespace = "http://ws.chinaunicom.cn/SrenewSer/unibssBody", partName = "parameters")
    public cn.chinaunicom.ws.srenewser.unibssbody.SRENEWSUBOUTPUT srenewSub(
        @WebParam(partName = "parameters", name = "SRENEW_SUB_INPUT", targetNamespace = "http://ws.chinaunicom.cn/SrenewSer/unibssBody")
        cn.chinaunicom.ws.srenewser.unibssbody.SRENEWSUBINPUT parameters
    );
}
