
/*
 * 
 */

package cn.chinaunicom.ws.srenewser;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.12
 * Tue Apr 17 09:41:55 GMT+08:00 2018
 * Generated source version: 2.2.12
 * 
 */


@WebServiceClient(name = "SrenewSer", 
                  wsdlLocation = "classpath:META-INF/SrenewSer/META-INF/SrenewSer.wsdl",
                  targetNamespace = "http://ws.chinaunicom.cn/SrenewSer/") 
public class SrenewSer_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://ws.chinaunicom.cn/SrenewSer/", "SrenewSer");
    public final static QName SrenewSerSOAP = new QName("http://ws.chinaunicom.cn/SrenewSer/", "SrenewSerSOAP");
    static {
        URL url = null;
        try {
            url = new URL("classpath:META-INF/SrenewSer/META-INF/SrenewSer.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:SrenewSer.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SrenewSer_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SrenewSer_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SrenewSer_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SrenewSer_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    public SrenewSer_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SrenewSer_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SrenewSer
     */
    @WebEndpoint(name = "SrenewSerSOAP")
    public SrenewSer getSrenewSerSOAP() {
        return super.getPort(SrenewSerSOAP, SrenewSer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SrenewSer
     */
    @WebEndpoint(name = "SrenewSerSOAP")
    public SrenewSer getSrenewSerSOAP(WebServiceFeature... features) {
        return super.getPort(SrenewSerSOAP, SrenewSer.class, features);
    }

}
